# Generated by Django 4.1.4 on 2023-05-03 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lecture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='URL')),
                ('content_lecture', models.FileField(upload_to='uploads_Lecture/%Y/%m/%d/', verbose_name='Файлы лекций')),
                ('content_laboratory', models.FileField(null=True, upload_to='uploads_Laboratory/%Y/%m/%d/', verbose_name='Файлы лабораторных работ')),
                ('time_create', models.DateTimeField(auto_now_add=True, verbose_name='Время создания')),
                ('time_update', models.DateTimeField(auto_now=True, verbose_name='Время обновления')),
                ('is_published', models.BooleanField(default=True, verbose_name='Опубликован\\Неопубликован')),
            ],
            options={
                'verbose_name': 'Лекции',
                'verbose_name_plural': 'Лекции',
                'ordering': ['time_create', 'title'],
            },
        ),
    ]
